name: Build and Deploy Storybook to GitHub Pages

on:
  push:
    branches:
      - 'main'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_and_deploy:
    name: Build and Deploy Storybook to GitHub pages
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Set up PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependency
        shell: bash
        run: pnpm install

      - name: Build storybook
        shell: bash
        run: pnpm build-storybook

      - name: Upload
        uses: actions/upload-pages-artifact@v1.0.4
        with: 
          path: storybook-static

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          token: ${{ github.token }}
